# Generated by Django 5.1.5 on 2025-01-23 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_image', models.ImageField(upload_to='house_images/')),
                ('house_video', models.FileField(blank=True, null=True, upload_to='house_videos/')),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('beds', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_leased', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leased_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
